[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:server]
command=uvicorn backend.server:app --reload
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:frontend]
command=/bin/sh -c "npm --prefix frontend/jbio-app install && npm --prefix frontend/jbio-app start"
environment=BROWSER="none"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
