[supervisord]
nodaemon=true

[program:server]
command=uvicorn backend.server:app --reload

[program:frontend]
command=/bin/sh -c "npm --prefix frontend/jbio-app install && npm --prefix frontend/jbio-app start"
environment=BROWSER="none"
redirect_stderr=true