name: python-setup
description: Common setup for python
runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.12'
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip