name: Test
on:
  pull_request:
    branches: ["main"]
jobs:
  python-test:
    runs-on: ubuntu-latest
    name: Pytest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4.2.2
    - uses: ./.github/workflows/common
    - name: Install pytest
      run: |
        pip install pytest -r requirements.txt
    - name: Run tests
      run: |
        pytest backend/tests
